import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{ts,tsx}",
    "./stories/**/*.{ts,tsx}",
    "../../apps/**/*.{ts,tsx,js,jsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "3xl": "1.5rem",
      },
      fontFamily: {
        body: ["system-ui", "sans-serif"],
        heading: ["system-ui", "sans-serif"],
      },
      fontSize: {
        "2xs": ["0.625rem", { lineHeight: "0.75rem" }],
      },
      boxShadow: {
        "hard-1": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        "hard-2": "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)",
        "hard-5": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--primary) / 0.05)",
          100: "hsl(var(--primary) / 0.1)",
          200: "hsl(var(--primary) / 0.2)",
          300: "hsl(var(--primary) / 0.3)",
          400: "hsl(var(--primary) / 0.4)",
          500: "hsl(var(--primary))",
          600: "hsl(var(--primary) / 1.1)",
          700: "hsl(var(--primary) / 1.2)",
          800: "hsl(var(--primary) / 1.3)",
          900: "hsl(var(--primary) / 1.4)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "hsl(var(--secondary) / 0.05)",
          100: "hsl(var(--secondary) / 0.1)",
          200: "hsl(var(--secondary) / 0.2)",
          300: "hsl(var(--secondary) / 0.3)",
          400: "hsl(var(--secondary) / 0.4)",
          500: "hsl(var(--secondary))",
          600: "hsl(var(--secondary) / 1.1)",
          700: "hsl(var(--secondary) / 1.2)",
          800: "hsl(var(--secondary) / 1.3)",
          900: "hsl(var(--secondary) / 1.4)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        error: {
          50: "#FEF2F2",
          100: "#FEE2E2",
          200: "#FECACA",
          300: "#FCA5A5",
          400: "#F87171",
          500: "#EF4444",
          600: "#DC2626",
          700: "#B91C1C",
          800: "#991B1B",
          900: "#7F1D1D",
        },
        success: {
          50: "#F0FDF4",
          100: "#DCFCE7",
          200: "#BBF7D0",
          300: "#86EFAC",
          400: "#4ADE80",
          500: "#22C55E",
          600: "#16A34A",
          700: "#15803D",
          800: "#166534",
          900: "#14532D",
        },
        warning: {
          50: "#FFFBEB",
          100: "#FEF3C7",
          200: "#FDE68A",
          300: "#FCD34D",
          400: "#FBBF24",
          500: "#F59E0B",
          600: "#D97706",
          700: "#B45309",
          800: "#92400E",
          900: "#78350F",
        },
        info: {
          50: "#EFF6FF",
          100: "#DBEAFE",
          200: "#BFDBFE",
          300: "#93C5FD",
          400: "#60A5FA",
          500: "#3B82F6",
          600: "#2563EB",
          700: "#1D4ED8",
          800: "#1E40AF",
          900: "#1E3A8A",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // GlueStack design tokens
        "background-0": "#FFFFFF",
        "background-50": "#F9FAFB",
        "background-100": "#F3F4F6",
        "background-200": "#E5E7EB",
        "background-300": "#D1D5DB",
        "background-400": "#9CA3AF",
        "background-500": "#6B7280",
        "background-600": "#4B5563",
        "background-700": "#374151",
        "background-800": "#1F2937",
        "background-900": "#111827",
        "background-dark": "rgba(0, 0, 0, 0.5)",
        "background-error": "#FEE2E2",
        "background-warning": "#FEF3C7",
        "background-success": "#DCFCE7",
        "background-info": "#DBEAFE",
        "background-muted": "#F3F4F6",
        "outline-0": "#FFFFFF",
        "outline-100": "#F9FAFB",
        "outline-200": "#F3F4F6",
        "outline-300": "#E5E7EB",
        "outline-400": "#D1D5DB",
        "typography-0": "#FFFFFF",
        "typography-50": "#F9FAFB",
        "typography-100": "#F3F4F6",
        "typography-200": "#E5E7EB",
        "typography-300": "#D1D5DB",
        "typography-400": "#9CA3AF",
        "typography-500": "#6B7280",
        "typography-600": "#4B5563",
        "typography-700": "#374151",
        "typography-800": "#1F2937",
        "typography-900": "#111827",
        "typography-950": "#030712",
        "indicator-primary": "#3B82F6",
        "indicator-error": "#EF4444",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
